#!/usr/bin/env python3
"""#277 — Walkthrough scheduling + iPad walkthrough reports (blueprint Build C,
ESTIMATING_DIVISION_BLUEPRINT §2 steps 4-5).

db_layer-aware, idempotent, dual-backend. Creates:

  * walkthrough_visit  — a scheduled walkthrough for an ESTIMATE (pre-project).
    attendee_user_id NOT NULL — someone from the company MUST physically attend
    (the operator's rule; enforced 400 at the endpoint too). site_poc_contact_id
    -> crm_contact when the site point-of-contact is in the CRM; poc_note free
    text when they aren't yet. Multiple visits per estimate BY DESIGN (revisits);
    history never deleted — cancelled is the correction. status scheduled|done|
    cancelled. Stage sync lives in walkthroughs.py: schedule -> est_stage
    walkthrough_scheduled, done -> walkthrough_done, cancel-with-no-other-
    scheduled -> back to received (the #276 machine stays the single truth).
    estimate.walkthrough_date becomes DERIVED from visits (synced server-side,
    never independently editable).
  * walkthrough_report — photos + notes captured on site (iPad), attached to the
    ESTIMATE (visit link optional — a report can land without a scheduled visit).
  * walkthrough_photo  — files under data_room/walkthroughs/<estimate_code>/
    (paths NEVER in JSON; gated by-id serves). Processed by the #235 pipeline
    (field_photos.process_image): HEIC-safe, orientation baked, GPS/EXIF STRIPPED
    from stored bytes, capture time kept (taken_at + estimated flag).

User-id columns carry no FK (the #264/#266 convention); clean typed parent links
(estimate/report/contact) do.

NO production cutover. Honors SSC_DB_URL (unset -> live, operator runs ONCE at
deploy AFTER snapshot — the deploy queue runs migrations in numeric order).

Run:  python apply_walkthroughs_277.py
"""
from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import db_layer  # noqa: E402
from apply_crm_266 import _table_exists  # noqa: E402
from apply_estimating_276 import ensure_estimating_schema  # noqa: E402


def ensure_walkthroughs_schema(conn) -> dict:
    """Create the three walkthrough tables. Idempotent + dual-backend; the #276
    base (estimate columns incl. est_stage/walkthrough_date) is ensured first."""
    ensure_estimating_schema(conn)

    pk = ("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if db_layer.is_postgres() else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    changed = {}

    changed["walkthrough_visit"] = not _table_exists(conn, "walkthrough_visit")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS walkthrough_visit (
              {pk},
              estimate_id         INTEGER NOT NULL REFERENCES estimate(id),
              visit_date          TEXT    NOT NULL,
              visit_time          TEXT,
              attendee_user_id    INTEGER NOT NULL,
              site_poc_contact_id INTEGER REFERENCES crm_contact(id),
              poc_note            TEXT,
              status              TEXT    DEFAULT 'scheduled',
              created_by          INTEGER,
              created_at          TEXT,
              updated_at          TEXT
            )""")
    # amendment (pre-deploy, same migration): visit_time LOCAL HH:MM, NULL = all-day —
    # additive for any DB that created the table before the amendment landed.
    from apply_crm_266 import _columns
    changed["visit_time"] = False
    if "visit_time" not in _columns(conn, "walkthrough_visit"):
        conn.execute("ALTER TABLE walkthrough_visit ADD COLUMN visit_time TEXT")
        changed["visit_time"] = True
    conn.execute("CREATE INDEX IF NOT EXISTS idx_wtvisit_estimate ON walkthrough_visit(estimate_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_wtvisit_date ON walkthrough_visit(visit_date)")

    changed["walkthrough_report"] = not _table_exists(conn, "walkthrough_report")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS walkthrough_report (
              {pk},
              estimate_id INTEGER NOT NULL REFERENCES estimate(id),
              visit_id    INTEGER REFERENCES walkthrough_visit(id),
              note        TEXT,
              created_by  INTEGER,
              created_at  TEXT
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_wtreport_estimate ON walkthrough_report(estimate_id)")

    changed["walkthrough_photo"] = not _table_exists(conn, "walkthrough_photo")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS walkthrough_photo (
              {pk},
              report_id          INTEGER NOT NULL REFERENCES walkthrough_report(id),
              file_path          TEXT,
              thumb_path         TEXT,
              file_name          TEXT,
              file_size          INTEGER,
              mime               TEXT,
              width              INTEGER,
              height             INTEGER,
              caption            TEXT,
              taken_at           TEXT,
              taken_at_estimated INTEGER DEFAULT 0,
              created_at         TEXT
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_wtphoto_report ON walkthrough_photo(report_id)")

    conn.commit()
    return changed


def main() -> int:
    conn = db_layer.connect()
    backend = "postgres" if db_layer.is_postgres() else "sqlite"
    try:
        changed = ensure_walkthroughs_schema(conn)
        ok = all(_table_exists(conn, t) for t in
                 ("walkthrough_visit", "walkthrough_report", "walkthrough_photo"))
        print(f"[277] backend={backend}  changed={changed}")
        print(f"[277] verify: 3 walkthrough tables -> {'OK' if ok else 'FAIL'}")
        return 0 if ok else 1
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
