#!/usr/bin/env python3
"""#264 — visibility-engine schema: item_visibility + item_redflag + visibility_audit.

db_layer-aware, idempotent, BOTH backends (SQLite default / Postgres via SSC_DB_URL),
following the #259/#260/#261/#263 dialect patterns. Default-deny BY CONSTRUCTION: a row in
item_visibility = shared to that audience; no row = internal-only. item_redflag is the sticky
"take offline" lever. See schema_item_visibility_264.sql for the column docs.

Idempotent: CREATE TABLE/INDEX IF NOT EXISTS (valid on both). The PRIMARY KEY clause is
emitted per backend (SQLite AUTOINCREMENT / Postgres GENERATED BY DEFAULT AS IDENTITY).
Reusable ensure_item_visibility_schema(conn) so the smoke can prepare its own DB.

NO production cutover. Honors SSC_DB_URL (unset -> live; sqlite:///copy / postgresql://...
-> isolated test DBs). Run:  python apply_item_visibility_264.py
"""
from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import db_layer  # noqa: E402


def _table_exists(conn, table: str) -> bool:
    if db_layer.is_postgres():
        return bool(conn.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=?",
            (table,)).fetchone())
    return bool(conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)).fetchone())


def ensure_item_visibility_schema(conn) -> dict:
    """Create the three visibility tables + indexes if missing. Idempotent, dual-backend.
    Returns {table: created_bool}. Caller owns the connection."""
    pk = ("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if db_layer.is_postgres() else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    changed = {}

    changed["item_visibility"] = not _table_exists(conn, "item_visibility")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS item_visibility (
              {pk},
              item_type   TEXT    NOT NULL,
              item_id     INTEGER NOT NULL,
              audience    TEXT    NOT NULL,
              shared_by   INTEGER,
              shared_at   TEXT,
              UNIQUE (item_type, item_id, audience)
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_itemvis_lookup ON item_visibility(item_type, item_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_itemvis_audience ON item_visibility(audience, item_type)")

    changed["item_redflag"] = not _table_exists(conn, "item_redflag")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS item_redflag (
              {pk},
              item_type   TEXT    NOT NULL,
              item_id     INTEGER NOT NULL,
              flagged_by  INTEGER,
              flagged_at  TEXT,
              UNIQUE (item_type, item_id)
            )""")

    changed["visibility_audit"] = not _table_exists(conn, "visibility_audit")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS visibility_audit (
              {pk},
              item_type   TEXT    NOT NULL,
              item_id     INTEGER NOT NULL,
              audience    TEXT,
              action      TEXT    NOT NULL,
              actor_id    INTEGER,
              at          TEXT
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_visaudit_item ON visibility_audit(item_type, item_id)")

    conn.commit()
    return changed


def main() -> int:
    conn = db_layer.connect()
    backend = "postgres" if db_layer.is_postgres() else "sqlite"
    try:
        changed = ensure_item_visibility_schema(conn)
        ok = all(_table_exists(conn, t) for t in
                 ("item_visibility", "item_redflag", "visibility_audit"))
        print(f"[264] backend={backend}  created={changed}")
        print(f"[264] verify: all three tables present -> {'OK' if ok else 'FAIL'}")
        return 0 if ok else 1
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
