#!/usr/bin/env python3
"""#272b — material consumption map: one additive table on top of the #272a ledger.

material_consumption_map maps ONE material to a drop-plan quantity driver so
consumption is DERIVED — the field never logs usage:

    driver 'volume_cf'   consumed = (Σ quantity_entries.volume_cf in window)
                                    ÷ yield_per_unit × (1 + waste_pct/100)
    driver 'area_sf'     same, over derived area (length×width unit-corrected, plus
                         flat entries logged with unit='SF')
    driver 'manual_rate' a FLAT per-workday rate for materials with no quantity
                         driver: yield_per_unit base-units/workday × (1 + waste_pct/100)

CATALOG RULE EXTENDS TO NUMBERS (operator-mandated): yields, waste factors, safety
days are PER-MATERIAL, OPERATOR-EDITED, blank until set — nothing seeded, nothing
hardcoded. No map = the material simply shows no burn/forecast (honest absence).
safety_days NULL means the code default (4). One map per material (UNIQUE).

Derivation is COMPUTE-ON-READ — no stored consumed quantity anywhere, so every number
a human sees traces back to quantity_entries rows × the operator's own map.

db_layer-aware, idempotent, dual-backend, additive. Exposes
ensure_consumption_schema(conn) for smokes.
Run:  python apply_material_consumption_272b.py     (SSC_DB_URL unset -> live)
"""
from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import db_layer  # noqa: E402


def _table_exists(conn, table: str) -> bool:
    if db_layer.is_postgres():
        return bool(conn.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=?",
            (table,)).fetchone())
    return bool(conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)).fetchone())


def ensure_consumption_schema(conn) -> dict:
    pk = ("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if db_layer.is_postgres() else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    changed = {"material_consumption_map": not _table_exists(conn, "material_consumption_map")}
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS material_consumption_map (
              {pk},
              material_id    INTEGER NOT NULL UNIQUE,
              driver         TEXT NOT NULL,
              yield_per_unit REAL NOT NULL,
              waste_pct      REAL NOT NULL DEFAULT 0,
              safety_days    INTEGER,
              notes          TEXT,
              updated_at     TEXT
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_mcm_material "
                 "ON material_consumption_map(material_id)")
    return changed


def main() -> int:
    backend = "postgres" if db_layer.is_postgres() else "sqlite"
    print(f"#272b material consumption map — backend={backend}")
    conn = db_layer.connect(pragma_fk=True)
    try:
        changed = ensure_consumption_schema(conn)
        conn.commit()
        for t, created in changed.items():
            print(f"  {t}: {'created' if created else 'already present (skipped)'}")
    finally:
        conn.close()
    print("done — additive (1 empty table); idempotent; safe to re-run.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
