#!/usr/bin/env python3
"""#278 — Project expense log (the C-Suite materials-cost source).

The materials module (#272) tracks QUANTITIES only — no costs, BY DESIGN (its
header says so). Costs live HERE: a per-project, C-Suite-only expense ledger
(date · vendor · category · amount · note) feeding the "Project Cost — Spent to
Date" widget. VOID-NOT-DELETE: rows are immutable once entered; a mistake is
voided (stamped who/when, audit note) and excluded from sums — the same ledger
discipline as material transactions. Comp-data governance (CLAUDE.md): this data
appears ONLY on the company console; every endpoint is admin/c_suite.

db_layer-aware, idempotent, dual-backend:

  project_expense(id PK, project_code NOT NULL, expense_date LOCAL YYYY-MM-DD,
    vendor TEXT, category CHECK IN ('materials','equipment','other'),
    amount REAL NOT NULL (Decimal in Python — REAL storage, penny math in code),
    note TEXT, entered_by_uid INT, voided_at TEXT NULL, voided_by_uid INT NULL,
    void_note TEXT NULL, created_at TEXT)

User-id columns carry no FK (the #264/#266 convention).

NO production cutover. Honors SSC_DB_URL (unset -> live, operator runs ONCE at
deploy AFTER snapshot — the deploy queue runs migrations in numeric order).

Run:  python apply_expenses_278.py
"""
from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import db_layer  # noqa: E402
from apply_crm_266 import _table_exists  # noqa: E402


def ensure_expenses_schema(conn) -> dict:
    """Create project_expense. Idempotent + dual-backend. Caller owns the conn."""
    pk = ("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if db_layer.is_postgres() else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    changed = {"project_expense": not _table_exists(conn, "project_expense")}
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS project_expense (
              {pk},
              project_code   TEXT NOT NULL,
              expense_date   TEXT NOT NULL,
              vendor         TEXT,
              category       TEXT NOT NULL CHECK (category IN ('materials','equipment','other')),
              amount         REAL NOT NULL,
              note           TEXT,
              entered_by_uid INTEGER,
              voided_at      TEXT,
              voided_by_uid  INTEGER,
              void_note      TEXT,
              created_at     TEXT
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_pexp_project ON project_expense(project_code)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_pexp_date ON project_expense(expense_date)")
    conn.commit()
    return changed


def main() -> int:
    conn = db_layer.connect()
    backend = "postgres" if db_layer.is_postgres() else "sqlite"
    try:
        changed = ensure_expenses_schema(conn)
        ok = _table_exists(conn, "project_expense")
        print(f"[278] backend={backend}  changed={changed}")
        print(f"[278] verify: project_expense -> {'OK' if ok else 'FAIL'}")
        return 0 if ok else 1
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
