#!/usr/bin/env python3
"""#274 — IRA inspection-pipeline schema: the post-award execution tracker + the
inspection calendar, both inside the #273 'estimates' company-console section.

db_layer-aware, idempotent, dual-backend (SQLite default / Postgres via SSC_DB_URL).
Creates / extends:

  * ira_job    — one row per CONVERTED IRA estimate (PK = project_code -> projects;
    estimate_id -> estimate). The checklist rail: CD-5 tracking (filing happens in
    DOB NOW — we TRACK status not_filed|filed|approved + filed date + the approved
    doc), COI + contract doc pointers (-> estimate_document, ONE consistent home for
    IRA paper), Fieldwire URL (integrate-don't-rebuild — link only, NO API in this
    build), report-sent date, payment strip (deposit 0/1 + date, balance open|paid,
    QB invoice ref).
  * ira_visit  — MULTIPLE visits per job BY DESIGN ("customer called us back for two
    more days" = add rows, never edit history). scheduled|performed|cancelled;
    performed visits immutable except status (enforced in ira.py). Visits are never
    hard-deleted — cancelled is the terminal correction.
  * estimate_document.expiry_date — additive column wiring the COI into the #271
    expiry machinery: the standard expired / expiring(30d) / on_file pill, computed
    at read time, and surfaced in the waiting-on digest sweep.
  * BACKFILL — an ira_job row for every already-converted IRA estimate (idempotent),
    so jobs converted under #273 appear on the Inspections board.

Dates LOCAL TEXT (CLAUDE.md dates rule). Doc-id columns carry real FKs (clean typed
parent links, per the #266 FK convention); user-id columns carry none.

NO production cutover. Honors SSC_DB_URL (unset -> live, operator runs ONCE at
deploy AFTER snapshot; sqlite:///copy / postgresql://...ssc_test -> the gate).

Run:  python apply_ira_274.py
"""
from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import db_layer  # noqa: E402
from apply_crm_266 import _columns, _table_exists  # noqa: E402
from apply_estimates_273 import ensure_estimates_schema  # noqa: E402


def ensure_ira_schema(conn) -> dict:
    """Create ira_job + ira_visit, add estimate_document.expiry_date, backfill jobs
    for converted IRA estimates. Idempotent and dual-backend. Caller owns the conn."""
    ensure_estimates_schema(conn)   # parent tables (estimate/estimate_document) first

    pk = ("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if db_layer.is_postgres() else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    changed = {}

    # ---- ira_job (PK = project_code; the checklist rail) ----
    changed["ira_job"] = not _table_exists(conn, "ira_job")
    conn.execute(
        """CREATE TABLE IF NOT EXISTS ira_job (
              project_code     TEXT    PRIMARY KEY REFERENCES projects(project_code),
              estimate_id      INTEGER REFERENCES estimate(id),
              cd5_status       TEXT    DEFAULT 'not_filed',
              cd5_filed_date   TEXT,
              cd5_doc_id       INTEGER REFERENCES estimate_document(id),
              coi_doc_id       INTEGER REFERENCES estimate_document(id),
              contract_doc_id  INTEGER REFERENCES estimate_document(id),
              fieldwire_url    TEXT,
              report_sent_date TEXT,
              deposit_received INTEGER DEFAULT 0,
              deposit_date     TEXT,
              balance_status   TEXT    DEFAULT 'open',
              qb_invoice_ref   TEXT,
              updated_at       TEXT
            )""")

    # ---- ira_visit (multi-visit by design; never hard-deleted) ----
    changed["ira_visit"] = not _table_exists(conn, "ira_visit")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS ira_visit (
              {pk},
              project_code TEXT    NOT NULL REFERENCES projects(project_code),
              visit_date   TEXT    NOT NULL,
              label        TEXT,
              status       TEXT    DEFAULT 'scheduled',
              created_by   INTEGER,
              created_at   TEXT
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_iravisit_project ON ira_visit(project_code)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_iravisit_date ON ira_visit(visit_date)")

    # ---- estimate_document.expiry_date (the #271 expiry machinery, for the COI) ----
    changed["estdoc_expiry_date"] = False
    if "expiry_date" not in _columns(conn, "estimate_document"):
        conn.execute("ALTER TABLE estimate_document ADD COLUMN expiry_date TEXT")
        changed["estdoc_expiry_date"] = True

    # ---- backfill: converted IRA estimates gain their job row (idempotent) ----
    rows = conn.execute(
        "SELECT id, converted_project_code FROM estimate "
        "WHERE est_type='IRA' AND status='converted' AND converted_project_code IS NOT NULL"
    ).fetchall()
    n_backfilled = 0
    for r in rows:
        if not conn.execute("SELECT 1 FROM ira_job WHERE project_code=?", (r[1],)).fetchone():
            conn.execute(
                "INSERT INTO ira_job (project_code, estimate_id, cd5_status, deposit_received, "
                "balance_status) VALUES (?,?, 'not_filed', 0, 'open')", (r[1], r[0]))
            n_backfilled += 1
    changed["jobs_backfilled"] = n_backfilled

    conn.commit()
    return changed


def main() -> int:
    conn = db_layer.connect()
    backend = "postgres" if db_layer.is_postgres() else "sqlite"
    try:
        changed = ensure_ira_schema(conn)
        ok = (_table_exists(conn, "ira_job") and _table_exists(conn, "ira_visit")
              and "expiry_date" in _columns(conn, "estimate_document"))
        print(f"[274] backend={backend}  created={changed}")
        print(f"[274] verify: ira_job + ira_visit + estimate_document.expiry_date -> {'OK' if ok else 'FAIL'}")
        return 0 if ok else 1
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
