#!/usr/bin/env python3
"""#263 — PM project-scoping schema: pm_project_assignment + projects.status.

db_layer-aware, idempotent, works on BOTH backends (SQLite default / Postgres via
SSC_DB_URL), following the #259/#260/#261 dialect patterns. Creates:

  * pm_project_assignment(id, user_id, project_code, assigned_by, assigned_at) with
    UNIQUE(user_id, project_code) — the project-membership rows that scope a `pm` to
    the project(s) an admin/c_suite assigned. The PRIMARY KEY is emitted per backend
    (SQLite AUTOINCREMENT / Postgres GENERATED ... AS IDENTITY).
  * projects.status TEXT DEFAULT 'active' — guard-added if missing (already present on
    live; this is for fresh deploys). 'active' | 'closed'.

Idempotent: CREATE TABLE/INDEX IF NOT EXISTS (valid on both); the ADD COLUMN is guarded
by a BACKEND-AWARE column check (PRAGMA table_info is a no-op on Postgres -> read
information_schema there, same as #261). assigned_at carries NO SQL default — the app
writes a LOCAL ISO string at insert time (CLAUDE.md dates rule), so the DDL is dialect-
free apart from the PK clause.

NO production cutover. Honors SSC_DB_URL, so the SAME script serves:
  * unset           -> live superstars.db (operator runs ONCE at deploy, AFTER snapshot)
  * sqlite:///<copy> / postgresql://...ssc_test -> the isolated test DBs (the gate)

Run:  python apply_pm_assignment_263.py
"""
from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import db_layer  # noqa: E402  # env-driven layer (SQLite default), per #259/#260


def _columns(conn, table: str) -> set:
    """Column names for `table`, backend-aware. PRAGMA table_info is a no-op on
    Postgres (db_layer returns an empty cursor for PRAGMA), so read the catalog there."""
    if db_layer.is_postgres():
        rows = conn.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = ?",
            (table,),
        ).fetchall()
        return {r[0] for r in rows}
    return {r[1] for r in conn.execute(f"PRAGMA table_info({table})").fetchall()}


def _table_exists(conn, table: str) -> bool:
    if db_layer.is_postgres():
        row = conn.execute(
            "SELECT 1 FROM information_schema.tables "
            "WHERE table_schema = 'public' AND table_name = ?",
            (table,),
        ).fetchone()
        return bool(row)
    row = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name = ?", (table,)
    ).fetchone()
    return bool(row)


def ensure_pm_assignment_schema(conn) -> dict:
    """Create pm_project_assignment + indexes + ensure projects.status. Idempotent and
    dual-backend. Returns {what: bool_changed} for the log / smoke self-check. Caller
    owns the connection (so the smoke can pass its db_layer.connect())."""
    changed = {"pm_project_assignment": False, "projects_status": False}

    # PRIMARY KEY clause differs by backend; everything else is identical.
    pk = ("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if db_layer.is_postgres()
          else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    if not _table_exists(conn, "pm_project_assignment"):
        conn.execute(
            f"""CREATE TABLE IF NOT EXISTS pm_project_assignment (
                  {pk},
                  user_id       INTEGER NOT NULL,
                  project_code  TEXT    NOT NULL,
                  assigned_by   INTEGER,
                  assigned_at   TEXT,
                  UNIQUE (user_id, project_code)
                )"""
        )
        changed["pm_project_assignment"] = True
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_pmpa_user ON pm_project_assignment(user_id)")
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_pmpa_project ON pm_project_assignment(project_code)")

    # projects.status — guard-add for fresh deploys (already present on live).
    if "status" not in _columns(conn, "projects"):
        conn.execute("ALTER TABLE projects ADD COLUMN status TEXT DEFAULT 'active'")
        changed["projects_status"] = True

    conn.commit()
    return changed


def main() -> int:
    conn = db_layer.connect()
    backend = "postgres" if db_layer.is_postgres() else "sqlite"
    try:
        changed = ensure_pm_assignment_schema(conn)
        has_table = _table_exists(conn, "pm_project_assignment")
        cols = _columns(conn, "pm_project_assignment")
        pcols = _columns(conn, "projects")
        ok = (has_table
              and {"id", "user_id", "project_code", "assigned_by", "assigned_at"} <= cols
              and "status" in pcols)
        print(f"[263] backend={backend}  created pm_project_assignment={changed['pm_project_assignment']}  "
              f"added projects.status={changed['projects_status']}  indexes=ensured")
        print(f"[263] verify: table={has_table}  cols_ok={ {'id','user_id','project_code','assigned_by','assigned_at'} <= cols }  "
              f"projects.status={'status' in pcols}  -> {'OK' if ok else 'FAIL'}")
        return 0 if ok else 1
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
