#!/usr/bin/env python3
"""#294 — field photo reassignment history + edit tracking + the DCR
amended-after-issue flag.

AMEND, NEVER ERASE (the DCR-immutability posture applied to photos): changing
a photo's drop keeps working through the ONE existing assignment door
(/api/field-photos/assign); what this migration adds is the paper trail —

  field_photo_reassign   one row per photo per transition: from -> to drop,
                         actor, optional reason, the photo's upload batch key,
                         SECONDS-SINCE-UPLOAD (the operator's edit-rate-as-
                         software-feedback insight needs timing, not counts),
                         whether the action corrected a WHOLE upload batch,
                         and whether it amended an issued DCR's day.
  report_index gains     photo_amended / photo_amended_at — the honest marker
                         on an ISSUED DCR whose day's photo record was
                         re-drop'd after issue (allowed, flagged, audited).
  app_settings seeds     fp_reassign_alert_threshold (default 5 corrections /
                         user / rolling 7 days) — SETTABLE, never hardcoded.

Idempotent + dual-backend. Ensured at SERVER BOOT (#289 pattern) — no manual
step on deploy. Run standalone:  python apply_photo_reassign_294.py
"""
from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import db_layer  # noqa: E402
from apply_crm_266 import _columns, _table_exists  # noqa: E402

THRESHOLD_KEY = "fp_reassign_alert_threshold"
THRESHOLD_DEFAULT = "5"


def ensure_reassign_schema(conn) -> dict:
    pk = ("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if db_layer.is_postgres() else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    changed = {}

    changed["field_photo_reassign"] = not _table_exists(conn, "field_photo_reassign")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS field_photo_reassign (
              {pk},
              photo_id      INTEGER NOT NULL,
              project_code  TEXT NOT NULL,
              from_drop_id  TEXT,                -- NULL = was Unassigned
              to_drop_id    TEXT,                -- NULL = back to Unassigned
              actor_uid     INTEGER,
              reason        TEXT,
              batch_key     TEXT,                -- uploader_uid|uploaded_at of the photo's upload
              seconds_since_upload INTEGER,      -- the SHAPE signal: minutes = UI, days = habits
              whole_batch   INTEGER NOT NULL DEFAULT 0,  -- this action moved the ENTIRE upload
              dcr_amended   INTEGER NOT NULL DEFAULT 0,  -- this transition amended an issued DCR day
              created_at    TEXT                 -- LOCAL ISO (never UTC)
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_fpr_photo ON field_photo_reassign(photo_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_fpr_actor "
                 "ON field_photo_reassign(actor_uid, created_at)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_fpr_project "
                 "ON field_photo_reassign(project_code)")

    cols = _columns(conn, "report_index")
    if "photo_amended" not in cols:
        conn.execute("ALTER TABLE report_index ADD COLUMN photo_amended INTEGER NOT NULL DEFAULT 0")
        changed["report_index.photo_amended"] = True
    if "photo_amended_at" not in cols:
        conn.execute("ALTER TABLE report_index ADD COLUMN photo_amended_at TEXT")
        changed["report_index.photo_amended_at"] = True

    conn.execute("INSERT OR IGNORE INTO app_settings (key, value) VALUES (?, ?)"
                 if not db_layer.is_postgres() else
                 "INSERT INTO app_settings (key, value) VALUES (?, ?) ON CONFLICT (key) DO NOTHING",
                 (THRESHOLD_KEY, THRESHOLD_DEFAULT))
    conn.commit()
    return changed


def main() -> int:
    conn = db_layer.connect()
    backend = "postgres" if db_layer.is_postgres() else "sqlite"
    try:
        changed = ensure_reassign_schema(conn)
        ok = _table_exists(conn, "field_photo_reassign")
        ok = ok and {"photo_amended", "photo_amended_at"} <= _columns(conn, "report_index")
        thr = conn.execute("SELECT value FROM app_settings WHERE key=?",
                           (THRESHOLD_KEY,)).fetchone()
        print(f"[294] backend={backend}  changed={changed}")
        print(f"[294] verify: tables+columns -> {'OK' if ok else 'FAIL'}   "
              f"threshold={thr['value'] if thr else 'MISSING'}")
        return 0 if (ok and thr) else 1
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
