#!/usr/bin/env python3
"""#293 — Authorable elevations: drawing sets, sheets, and the elevation
draft/confirm state machine.

Adds the persistence for "upload the engineer's full drawing set, pick the
elevation sheets, get a traced grid per elevation":

  drawing_set    one uploaded multi-page PDF per project (stored under
                 data_room/drawing_sets/ via ssc_paths — relative rows, #287)
  drawing_sheet  one row per page: thumbnail/full-render paths, the label and
                 sheet number pre-filled from the PDF TEXT LAYER (never OCR),
                 an is_elevation flag the operator confirms or overrides
  elevation      gains face_label (free text: North, SE, ...), source_sheet_id,
                 region_json (which drawing ON the page is the subject — every
                 sheet carries an EXISTING and a PROPOSED elevation), and
                 status (draft | confirmed)

STATUS DEFAULT IS 'confirmed', DELIBERATELY. 'draft' is an authoring-flow
concept: only drawing_sets.py writes it, at draft creation. Every elevation
row that exists before this migration — and any row created outside the
authoring flow (the 890 seed script, test fixtures, a manual INSERT) — must
keep behaving exactly as it did pre-#293, and pre-#293 behavior is "externally
visible when traced". A DEFAULT of 'draft' would silently hide such rows from
architects and clients (drafts are internal-only), which smoke_markup_280
correctly fails on. Backfill therefore needs no status UPDATE at all: the
ALTER's default stamps every existing row 'confirmed', 890 North included.

face_label backfill maps the #280 single-letter faces to their display words
(N -> North, ...). Rows with an unknown face keep the face string itself as
the label, never NULL.

Idempotent + dual-backend (SQLite / Postgres). Ensured at SERVER BOOT
(server.py calls ensure_all) per the #289 pattern — no manual migration step
on deploy; the Render host self-migrates on first boot with the new code.

Run standalone:  python apply_drawing_author_293.py
"""
from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import db_layer  # noqa: E402
from apply_crm_266 import _columns, _table_exists  # noqa: E402

FACE_LABELS = {
    "N": "North", "S": "South", "E": "East", "W": "West",
    "NE": "Northeast", "NW": "Northwest", "SE": "Southeast", "SW": "Southwest",
    "ALL": "Full set",
}


def ensure_drawing_set_schema(conn) -> dict:
    """drawing_set + drawing_sheet. Caller owns the conn."""
    pk = ("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if db_layer.is_postgres() else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    changed = {}

    changed["drawing_set"] = not _table_exists(conn, "drawing_set")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS drawing_set (
              {pk},
              project_code   TEXT NOT NULL,
              filename       TEXT,                 -- ORIGINAL upload name, display only
              pdf_path       TEXT,                 -- RELATIVE under the data root (#287)
              page_count     INTEGER NOT NULL DEFAULT 0,
              note           TEXT,
              uploaded_by_uid INTEGER,
              uploaded_at    TEXT                  -- LOCAL ISO (never UTC)
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_dset_project ON drawing_set(project_code)")

    changed["drawing_sheet"] = not _table_exists(conn, "drawing_sheet")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS drawing_sheet (
              {pk},
              set_id       INTEGER NOT NULL,
              page_no      INTEGER NOT NULL,       -- 1-based, matches the PDF
              label        TEXT,                   -- pre-filled from the text layer
              sheet_number TEXT,                   -- 'A-001.00' etc., text layer
              is_elevation INTEGER NOT NULL DEFAULT 0,
              thumb_path   TEXT,                   -- RELATIVE (#287)
              image_path   TEXT,                   -- full-res page render, RELATIVE
              width_pt     REAL,
              height_pt    REAL,
              text_meta    TEXT                    -- JSON: faces seen, existing/proposed
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_dsheet_set ON drawing_sheet(set_id)")
    conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_dsheet_unique "
                 "ON drawing_sheet(set_id, page_no)")
    conn.commit()
    return changed


def ensure_elevation_extensions(conn) -> dict:
    """New elevation columns + face_label backfill. Idempotent per column."""
    cols = _columns(conn, "elevation")
    added = {}
    if "face_label" not in cols:
        conn.execute("ALTER TABLE elevation ADD COLUMN face_label TEXT")
        added["face_label"] = True
    if "source_sheet_id" not in cols:
        conn.execute("ALTER TABLE elevation ADD COLUMN source_sheet_id INTEGER")
        added["source_sheet_id"] = True
    if "region_json" not in cols:
        conn.execute("ALTER TABLE elevation ADD COLUMN region_json TEXT")
        added["region_json"] = True
    if "status" not in cols:
        # DEFAULT 'confirmed' — see the module docstring for why this is not 'draft'.
        conn.execute("ALTER TABLE elevation ADD COLUMN status TEXT NOT NULL DEFAULT 'confirmed'")
        added["status"] = True

    # face_label backfill: display words for known faces; the face itself otherwise.
    for face, label in FACE_LABELS.items():
        conn.execute("UPDATE elevation SET face_label=? WHERE face=? AND face_label IS NULL",
                     (label, face))
    conn.execute("UPDATE elevation SET face_label=face "
                 "WHERE face_label IS NULL AND face IS NOT NULL")
    # A pre-#293 row can never be a draft: anything NULL/empty (from a backend that
    # ignored the DEFAULT on existing rows, or a hand-edited row) is confirmed.
    conn.execute("UPDATE elevation SET status='confirmed' "
                 "WHERE status IS NULL OR status=''")
    conn.commit()
    return added


def ensure_all(conn) -> dict:
    """The boot-time entry point (server.py). One call, both pieces."""
    changed = ensure_drawing_set_schema(conn)
    changed.update(ensure_elevation_extensions(conn))
    return changed


def main() -> int:
    conn = db_layer.connect()
    backend = "postgres" if db_layer.is_postgres() else "sqlite"
    try:
        changed = ensure_all(conn)
        ok = (_table_exists(conn, "drawing_set") and _table_exists(conn, "drawing_sheet"))
        ecols = _columns(conn, "elevation")
        ok = ok and {"face_label", "source_sheet_id", "region_json", "status"} <= ecols
        n_unlabeled = conn.execute(
            "SELECT COUNT(*) AS n FROM elevation WHERE face_label IS NULL").fetchone()["n"]
        n_draft = conn.execute(
            "SELECT COUNT(*) AS n FROM elevation WHERE status='draft'").fetchone()["n"]
        print(f"[293] backend={backend}  changed={changed}")
        print(f"[293] verify: tables+columns -> {'OK' if ok else 'FAIL'}   "
              f"unlabeled={n_unlabeled}  drafts={n_draft}")
        return 0 if (ok and n_unlabeled == 0) else 1
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
