#!/usr/bin/env python3
"""#295 — sign-in hours edit history + the DCR hours-amended-after-issue flag.

AMEND, NEVER ERASE (the #294 posture applied to labor): correcting a day's
hours keeps working through the EXISTING sign-in doors (PUT/PATCH/DELETE on
/api/sign-ins/<id> — the Weekly Hours Log has used them for months); what this
migration adds is the paper trail —

  sign_in_edit      one row per operator correction: edit (from -> to times)
                    or remove (times captured, to_* NULL), actor, optional
                    reason, and whether the correction amended an issued DCR
                    day. Worker-app self sign-in/out is the ORIGINAL record,
                    not a correction — those doors never write here.
  report_index gains hours_amended / hours_amended_at — the honest marker on
                    an ISSUED DCR whose day's labor was corrected after issue
                    (allowed, flagged, audited, and AUTO RE-RENDERED so the
                    served artifact matches reality).

Idempotent + dual-backend. Ensured at SERVER BOOT (#289 pattern) — no manual
step on deploy. Run standalone:  python apply_hours_edit_295.py
"""
from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import db_layer  # noqa: E402
from apply_crm_266 import _columns, _table_exists  # noqa: E402


def ensure_hours_edit_schema(conn) -> dict:
    pk = ("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if db_layer.is_postgres() else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    changed = {}

    changed["sign_in_edit"] = not _table_exists(conn, "sign_in_edit")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS sign_in_edit (
              {pk},
              sign_in_id    INTEGER NOT NULL,     -- original row id (row may be gone after remove)
              employee_id   TEXT NOT NULL,
              project_code  TEXT NOT NULL,
              date          TEXT NOT NULL,        -- the day being corrected (YYYY-MM-DD)
              action        TEXT NOT NULL,        -- 'edit' | 'remove'
              from_time_in  TEXT,
              from_time_out TEXT,
              to_time_in    TEXT,                 -- NULL on remove
              to_time_out   TEXT,                 -- NULL on remove
              actor_uid     INTEGER,
              actor_role    TEXT,
              reason        TEXT,
              dcr_amended   INTEGER NOT NULL DEFAULT 0,  -- corrected a day with an ISSUED DCR
              created_at    TEXT                  -- LOCAL ISO (never UTC)
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_sie_day "
                 "ON sign_in_edit(project_code, date)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_sie_row ON sign_in_edit(sign_in_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_sie_actor "
                 "ON sign_in_edit(actor_uid, created_at)")

    cols = _columns(conn, "report_index")
    if "hours_amended" not in cols:
        conn.execute("ALTER TABLE report_index ADD COLUMN hours_amended INTEGER NOT NULL DEFAULT 0")
        changed["report_index.hours_amended"] = True
    if "hours_amended_at" not in cols:
        conn.execute("ALTER TABLE report_index ADD COLUMN hours_amended_at TEXT")
        changed["report_index.hours_amended_at"] = True

    conn.commit()
    return changed


def main() -> int:
    conn = db_layer.connect()
    backend = "postgres" if db_layer.is_postgres() else "sqlite"
    try:
        changed = ensure_hours_edit_schema(conn)
        ok = _table_exists(conn, "sign_in_edit")
        ok = ok and {"hours_amended", "hours_amended_at"} <= _columns(conn, "report_index")
        print(f"[295] backend={backend}  changed={changed}")
        print(f"[295] verify: table+columns -> {'OK' if ok else 'FAIL'}")
        return 0 if ok else 1
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
