#!/usr/bin/env python3
"""#273 — Estimate/bid tracking schema: the general estimate log + documents + the
IRA type-extension row.

db_layer-aware, idempotent, works on BOTH backends (SQLite default / Postgres via
SSC_DB_URL), following the #266/#272 dialect patterns. Creates:

  * estimate           — one row per inquiry the company bids, any type. Code series
    {TYPE}-{BORO}-{NNN} (e.g. IRA-BX-001): est_type from the in-code catalog
    (estimates.EST_TYPES — extensible), borough MN|BX|BK|QN|SI, seq an INTEGER
    allocated NUMERICALLY per (type, borough) — the CLAUDE.md zero-padded-ID rule
    (the E-00013 lesson) applies from day one. Status pipeline intake|scoping|
    submitted|approved|lost|converted, server-validated in estimates.py.
    status_changed_at powers the board's age-in-stage. client_org_id links the CRM
    org (#266) — estimates are CRM-linked, never a duplicate client registry.
  * estimate_document  — attachments (bid_file|drawing|addendum|roof_plan|contract|
    other + the #274 IRA artifact categories). File stored ON DISK under
    data_room/estimate_docs/<code>/ with a uuid name; file_path NEVER crosses the
    wire (#229/#247 pattern — served ONLY by the gated by-id route).
  * estimate_ira       — IRA-only extension row (PK = estimate_id). Other types have
    none; a future type extension adds its own table, additively.
  * crm_activity.function_tag — via ensure_crm_schema (#273 extension there): the
    pipeline's auto-logged activity rows are tagged 'sales'.

Dialect notes (per #260): dates stay TEXT (LOCAL ISO — CLAUDE.md dates rule), the
PRIMARY KEY clause is emitted per backend, FKs are the clean parent links only
(estimate.client_org_id/contact_id, estimate_document.estimate_id,
estimate_ira.estimate_id); created_by/uploaded_by user-id columns carry NO FK (same
choice as #264/#266 — teardown-simple). Reusable ensure_estimates_schema(conn) so
the smoke can prepare its own DB.

NO production cutover. Honors SSC_DB_URL:
  * unset           -> live superstars.db (operator runs ONCE at deploy, AFTER snapshot)
  * sqlite:///<copy> / postgresql://...ssc_test -> the isolated test DBs (the gate)

Run:  python apply_estimates_273.py
"""
from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import db_layer  # noqa: E402
from apply_crm_266 import ensure_crm_schema, _columns, _table_exists  # noqa: E402


def ensure_estimates_schema(conn) -> dict:
    """Create estimate + estimate_document + estimate_ira (+ ensure the CRM base incl.
    crm_activity.function_tag). Idempotent and dual-backend. Caller owns the conn."""
    # estimates link crm_organization/crm_contact — the CRM base must exist first
    # (also brings crm_activity.function_tag, the #273 extension in apply_crm_266).
    ensure_crm_schema(conn)

    pk = ("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if db_layer.is_postgres() else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    changed = {}

    # ---- estimate ----
    changed["estimate"] = not _table_exists(conn, "estimate")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS estimate (
              {pk},
              code                   TEXT    NOT NULL UNIQUE,
              est_type               TEXT    NOT NULL,
              borough                TEXT    NOT NULL,
              seq                    INTEGER NOT NULL,
              client_org_id          INTEGER NOT NULL REFERENCES crm_organization(id),
              contact_id             INTEGER REFERENCES crm_contact(id),
              building_address       TEXT,
              status                 TEXT    NOT NULL DEFAULT 'intake',
              qb_estimate_ref        TEXT,
              final_amount           REAL,
              submitted_date         TEXT,
              decided_date           TEXT,
              converted_project_code TEXT,
              notes                  TEXT,
              created_by             INTEGER,
              created_at             TEXT,
              updated_at             TEXT,
              status_changed_at      TEXT
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_estimate_series ON estimate(est_type, borough)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_estimate_status ON estimate(status)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_estimate_org ON estimate(client_org_id)")

    # ---- estimate_document (file on disk; path NEVER in JSON) ----
    changed["estimate_document"] = not _table_exists(conn, "estimate_document")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS estimate_document (
              {pk},
              estimate_id INTEGER NOT NULL REFERENCES estimate(id),
              category    TEXT    NOT NULL,
              title       TEXT,
              doc_type    TEXT,
              file_path   TEXT,
              file_name   TEXT,
              file_size   INTEGER,
              mime        TEXT,
              uploaded_by INTEGER,
              uploaded_at TEXT
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_estdoc_estimate ON estimate_document(estimate_id)")

    # ---- estimate_ira (IRA-only extension row; the additive pattern for future types) ----
    changed["estimate_ira"] = not _table_exists(conn, "estimate_ira")
    conn.execute(
        """CREATE TABLE IF NOT EXISTS estimate_ira (
              estimate_id          INTEGER PRIMARY KEY REFERENCES estimate(id),
              dob_registered_email TEXT,
              engineer_name        TEXT,
              scope_mode           TEXT,
              scope_value          REAL,
              internal_drop_calc   REAL
            )""")

    conn.commit()
    return changed


def main() -> int:
    conn = db_layer.connect()
    backend = "postgres" if db_layer.is_postgres() else "sqlite"
    try:
        changed = ensure_estimates_schema(conn)
        tables = ("estimate", "estimate_document", "estimate_ira")
        ok = (all(_table_exists(conn, t) for t in tables)
              and "function_tag" in _columns(conn, "crm_activity"))
        print(f"[273] backend={backend}  created={changed}")
        print(f"[273] verify: 3 tables + crm_activity.function_tag -> {'OK' if ok else 'FAIL'}")
        return 0 if ok else 1
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
