#!/usr/bin/env python3
"""#269 — client per-section access-grant schema: client_section_grant.

db_layer-aware, idempotent, BOTH backends (SQLite default / Postgres via SSC_DB_URL),
following the #263/#264 dialect patterns. DEFAULT-OFF BY CONSTRUCTION: a row = that
section is unlocked for that client on that project; no row = locked. A client with
zero rows stays hard-contained on /welcome (#267). See schema_client_grants_269.sql
for the column docs and the two-layer default-deny model.

Idempotent: CREATE TABLE/INDEX IF NOT EXISTS (valid on both). The PRIMARY KEY clause
is emitted per backend (SQLite AUTOINCREMENT / Postgres GENERATED BY DEFAULT AS
IDENTITY). Reusable ensure_client_grants_schema(conn) so smokes can prepare their
own isolated DBs.

ADDITIVE migration — creates one empty table + indexes; touches no existing row.
Honors SSC_DB_URL (unset -> live; sqlite:///copy / postgresql://... -> isolated).
Run:  python apply_client_grants_269.py
"""
from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import db_layer  # noqa: E402


def _table_exists(conn, table: str) -> bool:
    if db_layer.is_postgres():
        return bool(conn.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=?",
            (table,)).fetchone())
    return bool(conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)).fetchone())


def ensure_client_grants_schema(conn) -> dict:
    """Create client_section_grant + indexes if missing. Idempotent, dual-backend.
    Returns {table: created_bool}. Caller owns the connection."""
    pk = ("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if db_layer.is_postgres() else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    changed = {"client_section_grant": not _table_exists(conn, "client_section_grant")}
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS client_section_grant (
              {pk},
              user_id       INTEGER NOT NULL,
              project_code  TEXT    NOT NULL,
              section       TEXT    NOT NULL,
              granted_by    INTEGER,
              granted_at    TEXT,
              UNIQUE (user_id, project_code, section)
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_csg_user ON client_section_grant(user_id, project_code)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_csg_project ON client_section_grant(project_code, section)")
    return changed


def main() -> int:
    backend = "postgres" if db_layer.is_postgres() else "sqlite"
    print(f"#269 client_section_grant schema — backend={backend}")
    conn = db_layer.connect(pragma_fk=True)
    try:
        changed = ensure_client_grants_schema(conn)
        conn.commit()
        for t, created in changed.items():
            print(f"  {t}: {'created' if created else 'already present (skipped)'}")
    finally:
        conn.close()
    print("done — idempotent; safe to re-run.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
