#!/usr/bin/env python3
"""#289 (Cloud M3) — public-door hardening schema. Idempotent, dual-backend.

Adds:
  users.totp_secret     TEXT    — base32 TOTP shared secret (NULL = not enrolled)
  users.totp_enabled    INT 0/1 — enrollment CONFIRMED (a scanned+verified code)
  users.totp_recovery   TEXT    — JSON list of bcrypt-hashed one-time recovery codes
  users.force_sso       INT 0/1 — password path DISABLED; Google SSO only (#261)

  worker_device                 — device-bound worker-app tokens (PIN alone is no
                                  longer sufficient from an unprovisioned device).
    id, employee_id (NULL until a device redeems for a specific worker — the
    provisioning code is issued per WORKER by the operator), token_hash (bcrypt
    of the opaque device token; the plaintext lives only in the phone's
    localStorage), provision_code_hash (bcrypt of the one-time redeem code),
    label, status ('pending'|'active'|'revoked'), issued_by, issued_at,
    redeemed_at, revoked_at, last_seen_at.

  app_settings['worker_device_enforcement']  — '0' (default; grace so a deploy
    never strands the field crew) | '1' (unprovisioned devices refused). The
    operator flips this to '1' AFTER provisioning the crew's phones, as a hard
    pre-M5 (public DNS) gate. The per-device + per-worker PIN THROTTLE is always
    on regardless of this flag.

login_audit.event CHECK is widened (rebuild) to admit the new events:
  login_lockout, totp_fail, totp_recovery_used, device_provisioned,
  device_revoked, pin_fail, pin_lockout.

NOTE (comp-data governance, CLAUDE.md): the TOTP secret is a shared secret. Like
pay rates it lives on the BitLocker-encrypted workstation only; SQLCipher at rest
is the tracked roadmap item. It is NEVER logged, never emitted in a payload, and
never leaves via any route — only the otpauth:// URI is shown once at enrollment.
"""
from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import db_layer  # noqa: E402

NEW_LOGIN_EVENTS = (
    "login_success", "login_fail", "logout", "password_set", "password_reset",
    # #289
    "login_lockout", "totp_fail", "totp_recovery_used",
    "device_provisioned", "device_revoked", "pin_fail", "pin_lockout",
)


def _table_exists(conn, table: str) -> bool:
    if db_layer.is_postgres():
        return bool(conn.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=?",
            (table,)).fetchone())
    return bool(conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)).fetchone())


def _user_columns(conn) -> set:
    if db_layer.is_postgres():
        return {r[0] for r in conn.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema='public' AND table_name='users'").fetchall()}
    return {r[1] for r in conn.execute("PRAGMA table_info(users)").fetchall()}


def ensure_hardening_schema(conn) -> dict:
    """Create/extend all #289 objects. Idempotent, dual-backend. Caller owns the
    connection (no commit here). Returns {object: 'created'|'present'}."""
    pg = db_layer.is_postgres()
    out = {}

    # ---- 1) users columns (ADD COLUMN is FK-safe + row-preserving on both) ----
    cols = _user_columns(conn)
    for name, ddl in (
        ("totp_secret", "TEXT"),
        ("totp_enabled", "INTEGER NOT NULL DEFAULT 0"),
        ("totp_recovery", "TEXT"),
        ("force_sso", "INTEGER NOT NULL DEFAULT 0"),
    ):
        if name not in cols:
            conn.execute(f"ALTER TABLE users ADD COLUMN {name} {ddl}")
            out[f"users.{name}"] = "created"
        else:
            out[f"users.{name}"] = "present"

    # ---- 2) worker_device table ----
    pk = ("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if pg else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    out["worker_device"] = "present" if _table_exists(conn, "worker_device") else "created"
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS worker_device (
              {pk},
              employee_id         TEXT,
              token_hash          TEXT,
              provision_code_hash TEXT,
              label               TEXT,
              status              TEXT NOT NULL DEFAULT 'pending',
              issued_by           INTEGER,
              issued_at           TEXT,
              redeemed_at         TEXT,
              revoked_at          TEXT,
              last_seen_at        TEXT
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_wdev_emp ON worker_device(employee_id, status)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_wdev_status ON worker_device(status)")

    # ---- 3) app_settings default (grace = OFF so a deploy can't strand the crew) ----
    row = conn.execute("SELECT value FROM app_settings WHERE key='worker_device_enforcement'").fetchone()
    if not row:
        conn.execute("INSERT INTO app_settings (key, value) VALUES ('worker_device_enforcement','0')")
        out["app_settings.worker_device_enforcement"] = "created(0)"
    else:
        out["app_settings.worker_device_enforcement"] = f"present({row[0]})"

    # ---- 4) widen the login_audit.event CHECK (SQLite rebuild; PG drop+add) ----
    out["login_audit.check"] = _widen_login_audit_check(conn, pg)
    return out


def _login_audit_check_ok(conn, pg) -> bool:
    """Probe: does the CHECK already admit a #289 event? (Insert+rollback a canary.)"""
    try:
        conn.execute("SAVEPOINT c289" if not pg else "SAVEPOINT c289")
        conn.execute("INSERT INTO login_audit (user_id, event, at) VALUES (NULL, 'login_lockout', '289probe')")
        conn.execute("ROLLBACK TO c289")
        conn.execute("RELEASE c289")
        return True
    except Exception:
        try:
            conn.execute("ROLLBACK TO c289"); conn.execute("RELEASE c289")
        except Exception:
            pass
        return False


def _widen_login_audit_check(conn, pg) -> str:
    if _login_audit_check_ok(conn, pg):
        return "present"
    events_sql = ",".join(f"'{e}'" for e in NEW_LOGIN_EVENTS)
    if pg:
        # Drop the old named/unnamed CHECK and add a fresh one.
        rows = conn.execute(
            "SELECT conname FROM pg_constraint WHERE conrelid='login_audit'::regclass AND contype='c'"
        ).fetchall()
        for (name,) in rows:
            conn.execute(f'ALTER TABLE login_audit DROP CONSTRAINT "{name}"')
        conn.execute(f"ALTER TABLE login_audit ADD CONSTRAINT login_audit_event_ck "
                     f"CHECK (event IN ({events_sql}))")
        return "widened(pg)"
    # SQLite: table rebuild preserving rows + id.
    conn.execute("ALTER TABLE login_audit RENAME TO login_audit_old_289")
    conn.execute(
        f"""CREATE TABLE login_audit (
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              user_id INTEGER,
              event TEXT NOT NULL CHECK (event IN ({events_sql})),
              at TEXT NOT NULL,
              ip TEXT, method TEXT,
              FOREIGN KEY (user_id) REFERENCES users(id)
            )""")
    # Re-insert, dropping any pre-existing FK-orphan rows (user_id pointing at a
    # deleted user) — the new table declares the FK, and those orphans predate it.
    # An isolated gate copy inherits such orphans (the #262/#266 lesson); this is
    # the same posture clean_user_orphans takes. NULL user_id (unknown-email fails)
    # is legitimate and preserved.
    conn.execute("INSERT INTO login_audit (id, user_id, event, at, ip, method) "
                 "SELECT id, user_id, event, at, ip, method FROM login_audit_old_289 "
                 "WHERE user_id IS NULL OR user_id IN (SELECT id FROM users)")
    conn.execute("DROP TABLE login_audit_old_289")
    return "widened(sqlite-rebuild)"


def main() -> int:
    backend = "postgres" if db_layer.is_postgres() else "sqlite"
    print(f"#289 public-hardening schema — backend={backend}")
    conn = db_layer.connect(pragma_fk=True)
    try:
        out = ensure_hardening_schema(conn)
        conn.commit()
        for k, v in out.items():
            print(f"  {k}: {v}")
    finally:
        conn.close()
    print("done — idempotent; safe to re-run.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
