#!/usr/bin/env python3
"""#266 — CRM/ops core schema: the four primitives + a project->client link.

db_layer-aware, idempotent, works on BOTH backends (SQLite default / Postgres via
SSC_DB_URL), following the #263/#264 dialect patterns. Creates:

  * crm_organization  — the tracked entity (client|vendor|lead|architect|engineer|sub|
    partner|other); status + a free/enum stage (prospect|proposal|onboarding|active|
    closed) for months-long onboarding; function_tags (comma-joined multi:
    finance|sales|compliance|ops|exec) for future role-slicing.
  * crm_contact       — a person (NOT a login — CRM tracking only, separate from users);
    org_id nullable FK -> crm_organization(id).
  * crm_activity      — the timeline: polymorphic (entity_type organization|contact|
    project + entity_id); note|call|email|meeting|stage_change|system; occurred_at LOCAL.
  * crm_task          — follow-ups/next-actions: polymorphic (entity_type + nullable
    entity_id, or 'none'); due_date LOCAL; status open|done; priority; function_tag.
  * projects.client_org_id — nullable FK -> crm_organization(id) (additive; existing
    projects unaffected).

Dialect notes (per #260): dates stay TEXT (the app writes LOCAL ISO — CLAUDE.md dates
rule; no SQL default), the PRIMARY KEY clause is emitted per backend, and the only FKs
are the clean parent links (contact.org_id, projects.client_org_id); the polymorphic
activity/task entity_id and the user-id columns carry NO FK (same choice as #264 — keeps
teardown simple and the entity_id can point at org/contact/project). Reusable
ensure_crm_schema(conn) so the smoke can prepare its own DB.

NO production cutover. Honors SSC_DB_URL:
  * unset           -> live superstars.db (operator runs ONCE at deploy, AFTER snapshot)
  * sqlite:///<copy> / postgresql://...ssc_test -> the isolated test DBs (the gate)

Run:  python apply_crm_266.py
"""
from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import db_layer  # noqa: E402  # env-driven layer (SQLite default), per #259/#260


def _columns(conn, table: str) -> set:
    """Column names for `table`, backend-aware (PRAGMA is a no-op on Postgres)."""
    if db_layer.is_postgres():
        rows = conn.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = ?",
            (table,),
        ).fetchall()
        return {r[0] for r in rows}
    return {r[1] for r in conn.execute(f"PRAGMA table_info({table})").fetchall()}


def _table_exists(conn, table: str) -> bool:
    if db_layer.is_postgres():
        return bool(conn.execute(
            "SELECT 1 FROM information_schema.tables "
            "WHERE table_schema = 'public' AND table_name = ?", (table,)).fetchone())
    return bool(conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name = ?", (table,)).fetchone())


def ensure_crm_schema(conn) -> dict:
    """Create the four CRM tables + indexes + ensure projects.client_org_id. Idempotent
    and dual-backend. Returns {what: bool_changed}. Caller owns the connection (so the
    smoke can pass its own db_layer.connect())."""
    pk = ("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if db_layer.is_postgres() else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    changed = {}

    # ---- crm_organization (parent — must exist before contact/projects FK) ----
    changed["crm_organization"] = not _table_exists(conn, "crm_organization")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS crm_organization (
              {pk},
              name              TEXT    NOT NULL,
              relationship_type TEXT,
              status            TEXT    DEFAULT 'active',
              stage             TEXT,
              function_tags     TEXT,
              notes             TEXT,
              created_at        TEXT,
              created_by        INTEGER
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_crmorg_reltype ON crm_organization(relationship_type)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_crmorg_stage ON crm_organization(stage)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_crmorg_status ON crm_organization(status)")

    # ---- crm_contact (FK -> crm_organization) ----
    changed["crm_contact"] = not _table_exists(conn, "crm_contact")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS crm_contact (
              {pk},
              org_id            INTEGER REFERENCES crm_organization(id),
              full_name         TEXT    NOT NULL,
              email             TEXT,
              phone             TEXT,
              title             TEXT,
              relationship_type TEXT,
              status            TEXT    DEFAULT 'active',
              notes             TEXT,
              created_at        TEXT,
              created_by        INTEGER
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_crmcontact_org ON crm_contact(org_id)")

    # ---- crm_activity (polymorphic timeline; no FK on entity_id) ----
    changed["crm_activity"] = not _table_exists(conn, "crm_activity")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS crm_activity (
              {pk},
              entity_type    TEXT    NOT NULL,
              entity_id      INTEGER NOT NULL,
              activity_type  TEXT    NOT NULL,
              summary        TEXT,
              body           TEXT,
              author_user_id INTEGER,
              occurred_at    TEXT,
              created_at     TEXT
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_crmact_entity ON crm_activity(entity_type, entity_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_crmact_occurred ON crm_activity(occurred_at)")

    # ---- crm_task (follow-ups; polymorphic, entity_id nullable) ----
    changed["crm_task"] = not _table_exists(conn, "crm_task")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS crm_task (
              {pk},
              entity_type      TEXT,
              entity_id        INTEGER,
              title            TEXT    NOT NULL,
              detail           TEXT,
              due_date         TEXT,
              assignee_user_id INTEGER,
              status           TEXT    DEFAULT 'open',
              priority         TEXT    DEFAULT 'normal',
              function_tag     TEXT,
              created_by       INTEGER,
              created_at       TEXT,
              completed_at     TEXT
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_crmtask_status ON crm_task(status)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_crmtask_assignee ON crm_task(assignee_user_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_crmtask_entity ON crm_task(entity_type, entity_id)")

    # ---- projects.client_org_id (additive FK -> crm_organization) ----
    changed["projects_client_org_id"] = False
    if "client_org_id" not in _columns(conn, "projects"):
        conn.execute("ALTER TABLE projects ADD COLUMN client_org_id INTEGER REFERENCES crm_organization(id)")
        changed["projects_client_org_id"] = True
    conn.execute("CREATE INDEX IF NOT EXISTS idx_projects_clientorg ON projects(client_org_id)")

    conn.commit()
    return changed


def main() -> int:
    conn = db_layer.connect()
    backend = "postgres" if db_layer.is_postgres() else "sqlite"
    try:
        changed = ensure_crm_schema(conn)
        tables = ("crm_organization", "crm_contact", "crm_activity", "crm_task")
        ok = (all(_table_exists(conn, t) for t in tables)
              and "client_org_id" in _columns(conn, "projects"))
        print(f"[266] backend={backend}  created={changed}")
        print(f"[266] verify: 4 tables present + projects.client_org_id -> {'OK' if ok else 'FAIL'}")
        return 0 if ok else 1
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
