#!/usr/bin/env python3
"""#272a — Materials & Deliveries schema: material catalog + txn ledger + expected
deliveries.

db_layer-aware, idempotent, dual-backend, ADDITIVE (three new empty tables; no existing
row touched). Follows the #269/#271 apply-script pattern; exposes
ensure_materials_schema(conn) for smokes to prepare isolated DBs.

DESIGN (operator-mandated CATALOG RULE): NO material names/vendors/yields are seeded —
every project starts with an EMPTY catalog; materials are created per project in the UI
(or copied from another project). Units come from the expense taxonomy's canonical enum
(server.EXPENSE_UNITS) — enforced in code, no CHECK, so the enum can grow additively.

  material            — per-project catalog row. pack_qty converts purchase_unit ->
                        base_unit at ENTRY (e.g. pallet = 56 bags). pinned drives the
                        card board + the weekly count. Deactivate, never hard-delete
                        once transactions exist.
  material_txn        — the ledger. qty_base is SIGNED (delivery/pickup/transfer_in +,
                        return/transfer_out/writeoff -, count_adjust either) so
                        ON-HAND = SUM(qty_base) — derived, never stored. qty_entered/
                        unit_entered preserve what the operator typed. slip_path is a
                        server-side disk path (NEVER in JSON; served by a gated by-id
                        route). expense_link_id references expenses.id logically.
  expected_delivery   — the future materials@ agent's home: it will INSERT rows with
                        source='agent' as Tier-B proposals — NO schema change needed
                        (source + source_note exist now). status enum in code:
                        ordered|confirmed|arriving|received|cancelled.

No FKs (matches the #264/#269 engine tables: dual-backend simple, teardown-simple;
integrity enforced in code). Dates LOCAL ISO. Consumption derivation (#272b) will read
this ledger + the drop-plan quantities ADDITIVELY — nothing here changes for it.

Run:  python apply_materials_272.py          (SSC_DB_URL unset -> live)
"""
from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import db_layer  # noqa: E402


def _table_exists(conn, table: str) -> bool:
    if db_layer.is_postgres():
        return bool(conn.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=?",
            (table,)).fetchone())
    return bool(conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)).fetchone())


def ensure_materials_schema(conn) -> dict:
    """Create the three #272 tables + indexes if missing. Idempotent, dual-backend."""
    pk = ("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if db_layer.is_postgres() else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    changed = {t: not _table_exists(conn, t)
               for t in ("material", "material_txn", "expected_delivery")}
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS material (
              {pk},
              project_code   TEXT NOT NULL,
              name           TEXT NOT NULL,
              category       TEXT,
              purchase_unit  TEXT,
              base_unit      TEXT NOT NULL,
              pack_qty       REAL NOT NULL DEFAULT 1,
              default_vendor TEXT,
              lead_time_days INTEGER,
              pinned         INTEGER NOT NULL DEFAULT 0,
              active         INTEGER NOT NULL DEFAULT 1,
              created_at     TEXT,
              UNIQUE (project_code, name)
            )""")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS material_txn (
              {pk},
              project_code    TEXT NOT NULL,
              material_id     INTEGER NOT NULL,
              txn_type        TEXT NOT NULL,
              qty_base        REAL NOT NULL,
              qty_entered     REAL,
              unit_entered    TEXT,
              vendor          TEXT,
              txn_date        TEXT,
              expense_link_id INTEGER,
              slip_path       TEXT,
              note            TEXT,
              created_by      INTEGER,
              created_at      TEXT
            )""")
    conn.execute(
        f"""CREATE TABLE IF NOT EXISTS expected_delivery (
              {pk},
              project_code TEXT NOT NULL,
              material_id  INTEGER,
              vendor       TEXT,
              description  TEXT,
              qty          REAL,
              unit         TEXT,
              expected_date TEXT,
              status       TEXT NOT NULL DEFAULT 'ordered',
              source       TEXT NOT NULL DEFAULT 'manual',
              source_note  TEXT,
              created_by   INTEGER,
              created_at   TEXT,
              updated_at   TEXT
            )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_material_project ON material(project_code, active)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_mtxn_project ON material_txn(project_code, material_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_mtxn_material ON material_txn(material_id, txn_date)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_expdel_project "
                 "ON expected_delivery(project_code, status, expected_date)")
    return changed


def main() -> int:
    backend = "postgres" if db_layer.is_postgres() else "sqlite"
    print(f"#272a materials schema — backend={backend}")
    conn = db_layer.connect(pragma_fk=True)
    try:
        changed = ensure_materials_schema(conn)
        conn.commit()
        for t, created in changed.items():
            print(f"  {t}: {'created' if created else 'already present (skipped)'}")
    finally:
        conn.close()
    print("done — additive (3 empty tables); idempotent; safe to re-run.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
