#!/usr/bin/env python3
"""#259 — verified data migration: SQLite snapshot COPY -> Postgres.

READ-ONLY on the SQLite side (a snapshot copy; never the live DB). Steps:
  1. Introspect the snapshot schema (sqlite_master + table_info).
  2. Create Postgres tables translated from the SQLite DDL:
       INTEGER PRIMARY KEY AUTOINCREMENT -> INTEGER GENERATED BY DEFAULT AS IDENTITY,
       GENERATED ... VIRTUAL -> STORED, drop SQLite-only bits. Booleans stay INTEGER
       0/1 (consistent with the app), dates stay TEXT/ISO (LOCAL, never UTC). FK
       constraints are created LAST (after data + orphan cleanup).
  3. Load every table, parents before children, preserving ids, skipping GENERATED cols.
  4. Resolve FK orphans (pre-existing because SQLite ran FK-enforcement OFF): for each
     FK, NULL the child value if the column is nullable, else DELETE the orphan child
     row. Report exactly what was fixed. THEN add the FK constraints.
  5. setval() each identity/serial sequence to max(id).
  6. Verify per-table row counts (snapshot vs Postgres), accounting for cleaned orphans.

Usage:
  python migrate_sqlite_to_pg_259.py <sqlite_snapshot.db> <postgres_url> [--reset]
  (--reset drops & recreates the public schema in the target Postgres DB first.)
"""
from __future__ import annotations

import re
import sqlite3
import sys

import psycopg


# ---------- DDL translation ----------

def _strip_line_comments(text: str) -> str:
    out = []
    for line in text.splitlines():
        # drop '-- ...' to end of line, but not inside a string literal
        in_str = False
        cut = None
        i = 0
        while i < len(line):
            c = line[i]
            if c == "'":
                in_str = not in_str
            elif c == "-" and i + 1 < len(line) and line[i + 1] == "-" and not in_str:
                cut = i
                break
            i += 1
        out.append(line if cut is None else line[:cut])
    return "\n".join(out)


def _split_top_commas(body: str) -> list[str]:
    """Split a CREATE-TABLE body on TOP-LEVEL commas (respecting nested parens +
    string literals), so CHECK/GENERATED expressions stay intact."""
    items, buf, depth, in_str = [], [], 0, False
    for c in body:
        if c == "'":
            in_str = not in_str
        if not in_str:
            if c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
            elif c == "," and depth == 0:
                items.append("".join(buf).strip())
                buf = []
                continue
        buf.append(c)
    tail = "".join(buf).strip()
    if tail:
        items.append(tail)
    return items


def _translate_create(sql: str):
    """Translate a SQLite CREATE TABLE to Postgres DDL (no FKs). Returns
    (pg_create_sql, [(col, parent_table, parent_col), ...]) — FKs (table-level AND
    inline column-level) are captured to be added AFTER the data load + orphan cleanup."""
    sql = _strip_line_comments(sql)
    m = re.match(r'\s*CREATE\s+TABLE(?:\s+IF\s+NOT\s+EXISTS)?\s+"?(\w+)"?\s*\((.*)\)\s*;?\s*$',
                 sql, re.DOTALL | re.IGNORECASE)
    tname, body = m.group(1), m.group(2)
    fks = []
    out_items = []
    for it in _split_top_commas(body):
        s = it.strip()
        if not s:
            continue
        if re.match(r"^FOREIGN\s+KEY", s, re.IGNORECASE):
            mm = re.search(r'FOREIGN\s+KEY\s*\(\s*"?(\w+)"?\s*\)\s*REFERENCES\s+"?(\w+)"?\s*\(\s*"?(\w+)"?\s*\)',
                           s, re.IGNORECASE)
            if mm:
                fks.append((mm.group(1), mm.group(2), mm.group(3)))
            continue  # drop table-level FK (re-added later)
        mm = re.search(r'\bREFERENCES\s+"?(\w+)"?\s*\(\s*"?(\w+)"?\s*\)', s, re.IGNORECASE)
        if mm:  # inline column-level FK
            col = re.match(r'"?(\w+)"?', s).group(1)
            fks.append((col, mm.group(1), mm.group(2)))
            s = re.sub(r'\s*\bREFERENCES\s+"?\w+"?\s*\(\s*"?\w+"?\s*\)(?:\s+ON\s+\w+\s+\w+)*', "", s, flags=re.IGNORECASE).rstrip()
        # #259 — DATES STAY TEXT (LOCAL-never-UTC rule): the app stores ISO strings and
        # compares them as strings. A real PG timestamp/date would make psycopg return
        # datetime objects and break those string comparisons. So a column TYPE of
        # TIMESTAMP/DATETIME/DATE becomes TEXT, and DEFAULT CURRENT_TIMESTAMP yields text.
        s = re.sub(r'^("?\w+"?\s+)(?:TIMESTAMP|DATETIME|DATE)\b', r"\1TEXT", s, flags=re.IGNORECASE)
        s = re.sub(r"DEFAULT\s+CURRENT_TIMESTAMP", "DEFAULT (now())::text", s, flags=re.IGNORECASE)
        out_items.append(s)
    pg = f"CREATE TABLE {tname} (\n  " + ",\n  ".join(out_items) + "\n)"
    pg = re.sub(r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
                "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", pg, flags=re.IGNORECASE)
    pg = re.sub(r"\bAUTOINCREMENT\b", "", pg, flags=re.IGNORECASE)
    pg = re.sub(r"\bVIRTUAL\b", "STORED", pg, flags=re.IGNORECASE)
    return pg, fks


def _cols(scon, table):
    """Return (all_cols, insertable_cols) — generated cols are excluded from inserts."""
    info = scon.execute(f'PRAGMA table_xinfo("{table}")').fetchall()
    allc, ins = [], []
    for r in info:
        name = r[1]
        hidden = r[6] if len(r) > 6 else 0   # xinfo: hidden 2/3 == generated
        allc.append(name)
        if hidden in (0, 1):
            ins.append(name)
    return allc, ins


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    snap, pgurl = sys.argv[1], sys.argv[2]
    reset = "--reset" in sys.argv[3:]

    scon = sqlite3.connect(f"file:{snap}?mode=ro", uri=True)
    scon.row_factory = sqlite3.Row
    pg = psycopg.connect(pgurl, autocommit=False)
    pcur = pg.cursor()

    if reset:
        pcur.execute("DROP SCHEMA public CASCADE; CREATE SCHEMA public;")
        pg.commit()

    # tables in creation order (sqlite_master order is creation order)
    tables = [r[0] for r in scon.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY rowid").fetchall()]

    # 1+2) create tables (no FKs yet)
    all_fks = {}
    for t in tables:
        create_sql = scon.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (t,)).fetchone()[0]
        pg_sql, fks = _translate_create(create_sql)
        all_fks[t] = fks
        try:
            pcur.execute(pg_sql)
        except Exception as e:
            print(f"[schema] FAILED on table {t}:\n----\n{pg_sql}\n----\n{e}")
            raise
    pg.commit()
    print(f"[schema] created {len(tables)} tables (FKs deferred)")

    # 3) load data, preserving ids, skipping generated columns
    counts = {}
    for t in tables:
        allc, ins = _cols(scon, t)
        collist = ", ".join(f'"{c}"' for c in ins)
        ph = ", ".join(["%s"] * len(ins))
        rows = scon.execute(f'SELECT {", ".join(chr(34)+c+chr(34) for c in ins)} FROM "{t}"').fetchall()
        n = 0
        for row in rows:
            pcur.execute(f'INSERT INTO "{t}" ({collist}) VALUES ({ph})', tuple(row))
            n += 1
        counts[t] = n
    pg.commit()
    print(f"[data] loaded {sum(counts.values())} rows across {len(tables)} tables")

    # 4) resolve FK orphans, then add FK constraints
    fixed = []
    for t in tables:
        for (col, ptbl, pcol) in all_fks[t]:
            # is the child column nullable?
            nn = scon.execute(f'PRAGMA table_info("{t}")').fetchall()
            notnull = next((c[3] for c in nn if c[1] == col), 0)
            orph = pcur.execute(
                f'SELECT COUNT(*) FROM "{t}" c WHERE c."{col}" IS NOT NULL '
                f'AND NOT EXISTS (SELECT 1 FROM "{ptbl}" p WHERE p."{pcol}" = c."{col}")').fetchone()[0]
            if orph:
                if notnull:
                    pcur.execute(
                        f'DELETE FROM "{t}" c WHERE c."{col}" IS NOT NULL '
                        f'AND NOT EXISTS (SELECT 1 FROM "{ptbl}" p WHERE p."{pcol}" = c."{col}")')
                    fixed.append(f"{t}.{col}->{ptbl}.{pcol}: DELETED {orph} orphan row(s) (NOT NULL col)")
                else:
                    pcur.execute(
                        f'UPDATE "{t}" c SET "{col}"=NULL WHERE c."{col}" IS NOT NULL '
                        f'AND NOT EXISTS (SELECT 1 FROM "{ptbl}" p WHERE p."{pcol}" = c."{col}")')
                    fixed.append(f"{t}.{col}->{ptbl}.{pcol}: NULLed {orph} orphan ref(s) (nullable col)")
            pcur.execute(f'ALTER TABLE "{t}" ADD FOREIGN KEY ("{col}") REFERENCES "{ptbl}" ("{pcol}")')
    pg.commit()
    print(f"[fk] resolved {len(fixed)} orphan group(s); FK constraints added")
    for f in fixed:
        print("   -", f)

    # 4b) create views (depend on tables). Best-effort dialect translation of the
    # common SQLite funcs; a view that needs more is reported (not fatal).
    views = scon.execute("SELECT name, sql FROM sqlite_master WHERE type='view' ORDER BY rowid").fetchall()
    vok, vfail = 0, []
    for vname, vsql in views:
        v = _strip_line_comments(vsql)
        v = re.sub(r"GROUP_CONCAT\s*\(\s*([^,)]+?)\s*,\s*([^)]+?)\)", r"string_agg(\1::text, \2)", v, flags=re.IGNORECASE)
        v = re.sub(r"GROUP_CONCAT\s*\(\s*([^,)]+?)\s*\)", r"string_agg(\1::text, ',')", v, flags=re.IGNORECASE)
        v = re.sub(r"\bIFNULL\s*\(", "COALESCE(", v, flags=re.IGNORECASE)
        try:
            pcur.execute(v)
            pg.commit()
            vok += 1
        except Exception as e:
            pg.rollback()
            vfail.append(f"{vname}: {str(e).splitlines()[0][:90]}")
    print(f"[views] created {vok}/{len(views)} view(s)" + (f"; {len(vfail)} need manual dialect work:" if vfail else ""))
    for f in vfail:
        print("   [view-todo]", f)

    # 5) reset identity sequences to max(id)
    idcols = pcur.execute(
        "SELECT table_name, column_name FROM information_schema.columns "
        "WHERE is_identity='YES' AND table_schema='public'").fetchall()
    for tbl, col in idcols:
        pcur.execute(f'SELECT setval(pg_get_serial_sequence(%s, %s), '
                     f'COALESCE((SELECT MAX("{col}") FROM "{tbl}"), 1))', (tbl, col))
    pg.commit()
    print(f"[seq] reset {len(idcols)} identity sequence(s) to max(id)")

    # 6) verify per-table counts
    print("\n[verify] per-table row counts (snapshot vs postgres):")
    print(f"   {'table':<34} {'sqlite':>8} {'postgres':>9}  ok")
    mism = 0
    for t in tables:
        s = scon.execute(f'SELECT COUNT(*) FROM "{t}"').fetchone()[0]
        p = pcur.execute(f'SELECT COUNT(*) FROM "{t}"').fetchone()[0]
        ok = (s == p)
        if not ok:
            mism += 1
        print(f"   {t:<34} {s:>8} {p:>9}  {'OK' if ok else 'DIFF (orphans cleaned)'}")
    print(f"\n[verify] {len(tables)} tables; {mism} with a count delta (expected only on FK-orphan-cleaned tables)")
    scon.close()
    pg.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
